# Generated by Django 5.1 on 2024-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_fac', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('total', models.PositiveSmallIntegerField()),
                ('area', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('met_pago', models.CharField(max_length=100)),
                ('id_suc', models.CharField(max_length=100)),
                ('id_prod', models.CharField(max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('id_cli', models.CharField(max_length=100)),
                ('id_emp', models.CharField(max_length=100)),
            ],
        ),
    ]
